[image]
name = "ubuntu"
base = "ubuntu-latest"
image = "ghcr.io/bethropolis/podbox:ubuntu-latest"

[image.packages]
manager = "apt"
install = []

[container]
name = "ubuntu"
home = "~/containers/ubuntu"
shell = "/usr/bin/fish"

[integration]
wayland = true
audio = true
gpu = true
notify = true
clipboard = true
xdg_open = true
dbus = true
ssh_agent = true
gpg_agent = true
sync_themes = true
sync_icons = true
sync_fonts = true

[integration.xdg_dirs]
documents = true
downloads = true
pictures = true
music = true
videos = true
desktop = true
projects = true

[dbus]
preset = "gnome"

[lifecycle]
quadlet = true
autostart = true