ARG BASE_IMAGE=fedora:44
FROM ${BASE_IMAGE}

ARG TARGETARCH
ARG TARGETVARIANT

# The guest binary must be placed in the build context before building.
#   cargo build -p podmgr-guest --release --target x86_64-unknown-linux-musl
#   cp target/x86_64-unknown-linux-musl/release/podmgr-guest .
COPY podmgr-guest /usr/local/bin/podmgr-guest

ENTRYPOINT ["/usr/local/bin/podmgr-guest", "--entry"]
CMD ["/bin/bash"]
