// Prebuild sync (run with bun): keeps a single markdown source of truth.
// 1. Copies ../docs/*.md        -> src/content/docs/
// 2. Copies ../docs/assets/*     -> public/assets/
// 3. Copies install-online.sh    -> public/install.sh  (must keep serving /podbox/install.sh)
// 4. Regenerates src/design/searchIndex.ts from the markdown headings,
//    using the SAME slug algorithm as MarkdownRenderer so palette anchors
//    always match rendered heading ids.
import { readdirSync, readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { marked } from 'marked';

const ROOT = join(import.meta.dir, '..');
const DOCS_SRC = join(ROOT, '..', 'docs');
const CONTENT_DIR = join(ROOT, 'src', 'content', 'docs');
const ASSETS_DST = join(ROOT, 'public', 'assets');

mkdirSync(CONTENT_DIR, { recursive: true });
mkdirSync(ASSETS_DST, { recursive: true });

// Identical to slugify() in design/components/MarkdownRenderer.tsx
function slugify(text: string): string {
  return text.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-');
}

function plainHeading(text: string): string {
  return text.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1').replace(/`([^`]+)`/g, '$1');
}

function parseFrontmatter(raw: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!raw.startsWith('---\n')) return out;
  const end = raw.indexOf('\n---', 4);
  if (end === -1) return out;
  for (const line of raw.slice(4, end).split('\n')) {
    const m = line.match(/^(\w+):\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim();
  }
  return out;
}

interface Heading { id: string; text: string; level: number }
interface DocEntry { id: string; title: string; path: string; description: string; headings: Heading[] }

const entries: DocEntry[] = [];
for (const file of readdirSync(DOCS_SRC).filter((f) => f.endsWith('.md')).sort()) {
  const id = file.replace(/\.md$/, '');
  copyFileSync(join(DOCS_SRC, file), join(CONTENT_DIR, file));

  const raw = readFileSync(join(DOCS_SRC, file), 'utf8');
  const fm = parseFrontmatter(raw);
  // Strip frontmatter before lexing: marked would read it as a setext h2.
  const body = raw.replace(/^---\n[\s\S]*?\n---\n?/, '');
  const tokens = marked.lexer(body);
  const counts = new Map<string, number>();
  const headings: Heading[] = [];
  let h1 = '';
  for (const t of tokens) {
    if (t.type === 'heading') {
      const text = plainHeading(t.text);
      if (t.depth === 1 && !h1) h1 = text;
      const base = slugify(text);
      const n = counts.get(base) ?? 0;
      counts.set(base, n + 1);
      headings.push({ id: n === 0 ? base : `${base}-${n}`, text, level: t.depth });
    }
  }
  entries.push({
    id,
    title: fm.title || h1 || id,
    path: id === 'index' ? '/docs' : `/docs/${id}`,
    description: fm.description || '',
    headings: headings.filter((h) => h.level <= 3),
  });
}

// Assets + installer
for (const f of readdirSync(join(DOCS_SRC, 'assets'))) {
  copyFileSync(join(DOCS_SRC, 'assets', f), join(ASSETS_DST, f));
}
copyFileSync(join(ROOT, '..', 'scripts', 'install-online.sh'), join(ROOT, 'public', 'install.sh'));

// Social cards: X/Discord scrapers reject SVG og:image, so render a
// 1200x630 PNG from the cover SVG (requires rsvg-convert, present in CI).
try {
  const proc = Bun.spawnSync([
    'rsvg-convert',
    '-w', '1200',
    join(ROOT, 'public', 'podbox-cover-image.svg'),
    '-o', join(ROOT, 'public', 'og-image.png'),
  ]);
  if (proc.exitCode !== 0) throw new Error('rsvg-convert failed');
  console.log('rendered og-image.png');
} catch {
  console.warn('rsvg-convert unavailable, skipping og-image.png');
}

const out =
  `// GENERATED by scripts/sync-content.ts — do not edit by hand.\n` +
  `export interface SearchHeading { id: string; text: string; level: number }\n` +
  `export interface SearchDoc { id: string; title: string; path: string; description: string; headings: SearchHeading[] }\n` +
  `export const SEARCH_DOCS: SearchDoc[] = ${JSON.stringify(entries, null, 2)};\n`;
writeFileSync(join(ROOT, 'src', 'design', 'searchIndex.ts'), out);
console.log(`synced ${entries.length} docs + assets + install.sh + search index`);
