import type { StudioValues } from './useStudioState';
import type { MountItem, EnvVarItem, HostExecItem } from './types';

export function generateStudioToml(s: StudioValues): string {
    let t = `# podbox.toml — generated by podbox Studio\n\n`;

    // [image]
    t += `[image]\n`;
    if (s.imageType === 'preset') {
      t += `preset = "${s.selectedPresetDistro}"\n`;
    } else {
      t += `base = "${s.customImageBase}"\n`;
    }
    if (s.imageName && s.imageName !== s.containerName) {
      t += `name = "${s.imageName}"\n`;
    }
    if (s.imagePrebuiltRef) {
      t += `prebuilt = "${s.imagePrebuiltRef}"\n`;
    }
    if (s.pullRetry !== 3) t += `pull_retry = ${s.pullRetry}\n`;
    if (s.pullRetryDelay !== '5s') t += `pull_retry_delay = "${s.pullRetryDelay}"\n`;
    if (s.packageManager !== 'auto') t += `package_manager = "${s.packageManager}"\n`;

    if (s.packagesInstallList.length > 0) {
      t += `packages = [${s.packagesInstallList.map((p) => `"${p}"`).join(', ')}]\n`;
    }
    if (s.packagesRemoveList.length > 0) {
      t += `remove_packages = [${s.packagesRemoveList.map((p) => `"${p}"`).join(', ')}]\n`;
    }
    if (s.runCommands.trim()) {
      t += `run = [\n${s.runCommands
        .split('\n')
        .filter((r) => r.trim())
        .map((r) => `  "${r.trim()}",\n`)
        .join('')}]\n`;
    }

    // [container]
    t += `\n[container]\n`;
    t += `name = "${s.containerName}"\n`;
    if (s.containerHome) t += `home = "${s.containerHome}"\n`;
    if (s.containerShell) t += `shell = "${s.containerShell}"\n`;
    if (s.containerMemory) t += `memory = "${s.containerMemory}"\n`;
    if (s.containerCpus) t += `cpus = "${s.containerCpus}"\n`;
    if (s.containerReloadCmd) t += `reload_cmd = "${s.containerReloadCmd}"\n`;

    const validMounts = s.extraMounts.filter((m) => m.host.trim() && m.guest.trim());
    if (validMounts.length > 0) {
      t += `mounts = [\n${validMounts
        .map((m) => `  "${m.host}:${m.guest}:${m.mode || 'z'}",\n`)
        .join('')}]\n`;
    }

    const validEnvs = s.envVars.filter((e) => e.key.trim());
    if (validEnvs.length > 0) {
      t += `env = {\n${validEnvs
        .map((e) => `  ${e.key} = "${e.value}",\n`)
        .join('')}}\n`;
    }

    // [security]
    const hasSecurity =
      s.apparmor ||
      s.seccomp !== 'default' ||
      !s.secLabelDisable ||
      !s.noNewPrivileges ||
      s.readOnlyRootfs ||
      s.usernsMode !== 'keep-id' ||
      s.capPreset !== 'default' ||
      s.extraCapAddList.length > 0;
    if (hasSecurity) {
      t += `\n[security]\n`;
      if (s.apparmor) t += `s.apparmor = "${s.apparmor}"\n`;
      if (s.seccomp !== 'default') t += `s.seccomp = "${s.seccomp}"\n`;
      if (!s.secLabelDisable) t += `security_label_disable = false\n`;
      if (!s.noNewPrivileges) t += `no_new_privileges = false\n`;
      if (s.readOnlyRootfs) t += `read_only_rootfs = true\n`;
      if (s.usernsMode !== 'keep-id') t += `userns = "${s.usernsMode}"\n`;
      if (s.capPreset !== 'default') t += `cap_preset = "${s.capPreset}"\n`;
      if (s.extraCapAddList.length > 0) {
        t += `cap_add = [${s.extraCapAddList.map((c) => `"${c}"`).join(', ')}]\n`;
      }
    }

    // [network]
    const hasNet = s.netMode !== 'private' || s.portMappingsList.length > 0;
    if (hasNet) {
      t += `\n[network]\n`;
      t += `mode = "${s.netMode}"\n`;
      if (s.portMappingsList.length > 0 && s.netMode !== 'host') {
        t += `ports = [${s.portMappingsList.map((p) => `"${p}"`).join(', ')}]\n`;
      }
    }

    // [integration]
    t += `\n[integration]\n`;
    t += `wayland = ${s.intWayland}\n`;
    t += `audio = ${s.intAudio}\n`;
    t += `gpu = ${s.intGpu === 'true' || s.intGpu === 'false' ? s.intGpu : `"${s.intGpu}"`}\n`;
    t += `dbus = ${s.intDbus}\n`;
    if (!s.intNotify) t += `notify = false\n`;
    if (!s.intXdgOpen) t += `xdg_open = false\n`;
    if (!s.intClipboard) t += `clipboard = false\n`;
    if (!s.intSyncFonts) t += `sync_fonts = false\n`;
    if (!s.intSyncIcons) t += `sync_icons = false\n`;
    if (!s.intSyncThemes) t += `sync_themes = false\n`;
    if (s.intSshAgent) t += `ssh_agent = true\n`;
    if (s.intGpgAgent) t += `gpg_agent = true\n`;

    if (s.hostExecEnabled) {
      t += `\n[integration.host_exec]\n`;
      t += `enabled = true\n`;
      const validExecs = s.hostExecList.filter((e) => e.alias.trim() && e.path.trim());
      if (validExecs.length > 0) {
        t += `allowlist = { ${validExecs.map((e) => `${e.alias} = "${e.path}"`).join(', ')} }\n`;
      }
    }

    const hasXdgDirs =
      s.xdgDocuments || s.xdgDownloads || s.xdgPictures || s.xdgMusic || s.xdgVideos || s.xdgDesktop || s.xdgProjects;
    if (hasXdgDirs) {
      t += `\n[integration.xdg_dirs]\n`;
      if (s.xdgDocuments) t += `documents = true\n`;
      if (s.xdgDownloads) t += `downloads = true\n`;
      if (s.xdgPictures) t += `pictures = true\n`;
      if (s.xdgMusic) t += `music = true\n`;
      if (s.xdgVideos) t += `videos = true\n`;
      if (s.xdgDesktop) t += `desktop = true\n`;
      if (s.xdgProjects) t += `projects = true\n`;
    }

    if (s.exportAppsList.length > 0 || s.exportBinsList.length > 0) {
      t += `\n[integration.export]\n`;
      if (s.exportAppsList.length > 0) t += `apps = [${s.exportAppsList.map((a) => `"${a}"`).join(', ')}]\n`;
      if (s.exportBinsList.length > 0) t += `bins = [${s.exportBinsList.map((b) => `"${b}"`).join(', ')}]\n`;
    }

    // [lifecycle]
    const hasLifecycle =
      !s.lifeQuadlet || s.lifeAutostart || s.lifeOnStop !== 'keep' || s.lifeAutoUpdate || s.lifeIdleTimeout !== 'off';
    if (hasLifecycle) {
      t += `\n[lifecycle]\n`;
      if (!s.lifeQuadlet) t += `quadlet = false\n`;
      if (s.lifeAutostart) t += `autostart = true\n`;
      if (s.lifeOnStop !== 'keep') t += `on_stop = "${s.lifeOnStop}"\n`;
      if (s.lifeAutoUpdate) t += `auto_update = true\n`;
      if (s.lifeIdleTimeout !== 'off') t += `idle_timeout = "${s.lifeIdleTimeout}"\n`;
    }

    // [systemd]
    const reqList = s.sysRequires.split(',').map((s) => s.trim()).filter(Boolean);
    const afterList = s.sysAfter.split(',').map((s) => s.trim()).filter(Boolean);
    if (reqList.length > 0 || s.sysAfter !== 'network-online.target') {
      t += `\n[systemd]\n`;
      if (reqList.length > 0) t += `requires = [${reqList.map((r) => `"${r}"`).join(', ')}]\n`;
      if (afterList.length > 0) t += `after = [${afterList.map((a) => `"${a}"`).join(', ')}]\n`;
    }

    // [dbus]
    if (s.intDbus) {
      if (s.dbusPreset !== 'portal' || s.dbusTalkList.length > 0 || s.dbusOwnList.length > 0) {
        t += `\n[dbus]\n`;
        if (s.dbusPreset !== 'none') t += `preset = "${s.dbusPreset}"\n`;
        if (s.dbusTalkList.length > 0) t += `talk = [${s.dbusTalkList.map((tk) => `"${tk}"`).join(', ')}]\n`;
        if (s.dbusOwnList.length > 0) t += `own = [${s.dbusOwnList.map((o) => `"${o}"`).join(', ')}]\n`;
      }
    }

    // [wayland]
    if (s.intWayland && (!s.waylandFirewall || s.waylandBlockedList.length > 0)) {
      t += `\n[wayland]\n`;
      if (!s.waylandFirewall) t += `firewall = false\n`;
      if (s.waylandBlockedList.length > 0) {
        t += `blocked_interfaces = [\n${s.waylandBlockedList.map((b) => `  "${b}",\n`).join('')}]\n`;
      }
    }

    return t;
}
