// GENERATED by scripts/sync-content.ts — do not edit by hand.
export interface SearchHeading { id: string; text: string; level: number }
export interface SearchDoc { id: string; title: string; path: string; description: string; headings: SearchHeading[] }
export const SEARCH_DOCS: SearchDoc[] = [
  {
    "id": "architecture",
    "title": "Architecture",
    "path": "/docs/architecture",
    "description": "How podbox works — codegen pipeline, generated Containerfile and Quadlet units, host-guest socket protocol, UID mapping, and project structure.",
    "headings": [
      {
        "id": "architecture",
        "text": "Architecture",
        "level": 1
      },
      {
        "id": "how-it-works",
        "text": "How It Works",
        "level": 2
      },
      {
        "id": "codegen-pipeline",
        "text": "Codegen Pipeline",
        "level": 2
      },
      {
        "id": "generated-containerfile",
        "text": "Generated Containerfile",
        "level": 2
      },
      {
        "id": "build-context-layout",
        "text": "Build Context Layout",
        "level": 3
      },
      {
        "id": "generated-quadlet-files",
        "text": "Generated Quadlet Files",
        "level": 2
      },
      {
        "id": "myenvbuild",
        "text": "myenv.build",
        "level": 3
      },
      {
        "id": "myenvsocket",
        "text": "myenv.socket",
        "level": 3
      },
      {
        "id": "myenvcontainer",
        "text": "myenv.container",
        "level": 3
      },
      {
        "id": "host-guest-socket-protocol",
        "text": "Host-Guest Socket Protocol",
        "level": 2
      },
      {
        "id": "guest-daemon-podbox-guest",
        "text": "Guest Daemon (podbox-guest)",
        "level": 2
      },
      {
        "id": "daemon-startup-sequence",
        "text": "Daemon startup sequence",
        "level": 3
      },
      {
        "id": "uid-mapping",
        "text": "UID Mapping",
        "level": 2
      },
      {
        "id": "runtime-flow-full-sequence",
        "text": "Runtime Flow (Full Sequence)",
        "level": 2
      },
      {
        "id": "project-structure",
        "text": "Project Structure",
        "level": 2
      },
      {
        "id": "exit-codes",
        "text": "Exit Codes",
        "level": 2
      }
    ]
  },
  {
    "id": "baked-in-packages",
    "title": "Base packages",
    "path": "/docs/baked-in-packages",
    "description": "Packages podbox installs into custom-built images automatically — base tools, shells, locales, sudo, and timezone.",
    "headings": [
      {
        "id": "base-packages",
        "text": "Base packages",
        "level": 1
      },
      {
        "id": "whats-included",
        "text": "What's included",
        "level": 2
      },
      {
        "id": "distro-detection",
        "text": "Distro detection",
        "level": 2
      },
      {
        "id": "add-or-remove-packages",
        "text": "Add or remove packages",
        "level": 2
      },
      {
        "id": "passwordless-sudo",
        "text": "Passwordless sudo",
        "level": 2
      },
      {
        "id": "locale-and-timezone",
        "text": "Locale and timezone",
        "level": 2
      },
      {
        "id": "theme-icon-and-font-paths",
        "text": "Theme, icon, and font paths",
        "level": 2
      }
    ]
  },
  {
    "id": "cli",
    "title": "CLI reference",
    "path": "/docs/cli",
    "description": "podbox CLI reference — every command grouped by workflow, container name resolution, exit codes, JSON output, and shell completion.",
    "headings": [
      {
        "id": "cli-reference",
        "text": "CLI reference",
        "level": 1
      },
      {
        "id": "command-groups",
        "text": "Command groups",
        "level": 2
      },
      {
        "id": "naming-a-container",
        "text": "Naming a container",
        "level": 2
      },
      {
        "id": "exit-codes",
        "text": "Exit codes",
        "level": 2
      },
      {
        "id": "json-output",
        "text": "JSON output",
        "level": 2
      },
      {
        "id": "history",
        "text": "History",
        "level": 2
      },
      {
        "id": "shell-completion",
        "text": "Shell completion",
        "level": 2
      }
    ]
  },
  {
    "id": "config",
    "title": "Configuration Reference",
    "path": "/docs/config",
    "description": "Complete TOML configuration reference for podbox — all keys, defaults, and examples for image, container, integration, lifecycle, and D-Bus settings.",
    "headings": [
      {
        "id": "configuration-reference",
        "text": "Configuration Reference",
        "level": 1
      },
      {
        "id": "image",
        "text": "[image]",
        "level": 2
      },
      {
        "id": "imagepackages",
        "text": "[image.packages]",
        "level": 3
      },
      {
        "id": "imagerun",
        "text": "[image.run]",
        "level": 3
      },
      {
        "id": "container",
        "text": "[container]",
        "level": 2
      },
      {
        "id": "containermounts",
        "text": "[container.mounts]",
        "level": 3
      },
      {
        "id": "containerenv",
        "text": "[container.env]",
        "level": 3
      },
      {
        "id": "dotfiles",
        "text": "[dotfiles]",
        "level": 2
      },
      {
        "id": "security",
        "text": "[security]",
        "level": 2
      },
      {
        "id": "securitysecrets",
        "text": "[security].secrets",
        "level": 3
      },
      {
        "id": "network",
        "text": "[network]",
        "level": 2
      },
      {
        "id": "storageshared_caches",
        "text": "[storage.shared_caches]",
        "level": 2
      },
      {
        "id": "storagehost_caches",
        "text": "[storage.host_caches]",
        "level": 2
      },
      {
        "id": "integration",
        "text": "[integration]",
        "level": 2
      },
      {
        "id": "gpumode-values",
        "text": "GpuMode values",
        "level": 3
      },
      {
        "id": "integrationhardware",
        "text": "[integration.hardware]",
        "level": 3
      },
      {
        "id": "integrationhost_exec",
        "text": "[integration.host_exec]",
        "level": 3
      },
      {
        "id": "integrationxdg_dirs",
        "text": "[integration.xdg_dirs]",
        "level": 3
      },
      {
        "id": "integrationexport",
        "text": "[integration.export]",
        "level": 3
      },
      {
        "id": "lifecycle",
        "text": "[lifecycle]",
        "level": 2
      },
      {
        "id": "systemd",
        "text": "[systemd]",
        "level": 2
      },
      {
        "id": "dbus",
        "text": "[dbus]",
        "level": 2
      },
      {
        "id": "wayland",
        "text": "[wayland]",
        "level": 2
      },
      {
        "id": "full-example",
        "text": "Full Example",
        "level": 2
      }
    ]
  },
  {
    "id": "dbus-proxy",
    "title": "D-Bus Proxy",
    "path": "/docs/dbus-proxy",
    "description": "Filtered D-Bus access for podbox containers via xdg-dbus-proxy — configuration, allowed services, and security model.",
    "headings": [
      {
        "id": "d-bus-proxy",
        "text": "D-Bus Proxy",
        "level": 1
      },
      {
        "id": "how-it-works",
        "text": "How it works",
        "level": 2
      },
      {
        "id": "configuration",
        "text": "Configuration",
        "level": 2
      },
      {
        "id": "portal-access-model",
        "text": "Portal access model",
        "level": 2
      },
      {
        "id": "behavior-matrix",
        "text": "Behavior matrix",
        "level": 2
      },
      {
        "id": "generated-proxy-unit",
        "text": "Generated proxy unit",
        "level": 2
      },
      {
        "id": "requirements",
        "text": "Requirements",
        "level": 2
      },
      {
        "id": "verification",
        "text": "Verification",
        "level": 2
      },
      {
        "id": "test-an-allowed-service",
        "text": "Test an allowed service",
        "level": 3
      },
      {
        "id": "test-isolation",
        "text": "Test isolation",
        "level": 3
      },
      {
        "id": "portal-surface-audit",
        "text": "Portal surface audit",
        "level": 3
      }
    ]
  },
  {
    "id": "export",
    "title": "Desktop Integration (Export)",
    "path": "/docs/export",
    "description": "Export apps and binaries from podbox containers to your host desktop — .desktop files, launcher icons, binary shims, and MIME type handling.",
    "headings": [
      {
        "id": "desktop-integration-export",
        "text": "Desktop Integration (Export)",
        "level": 1
      },
      {
        "id": "commands",
        "text": "Commands",
        "level": 2
      },
      {
        "id": "app-export",
        "text": "App Export",
        "level": 2
      },
      {
        "id": "how-it-works",
        "text": "How it works",
        "level": 3
      },
      {
        "id": "mime-types",
        "text": "MIME types",
        "level": 3
      },
      {
        "id": "binary-export",
        "text": "Binary Export",
        "level": 2
      },
      {
        "id": "generated-shim",
        "text": "Generated shim",
        "level": 3
      },
      {
        "id": "cleanup",
        "text": "Cleanup",
        "level": 2
      }
    ]
  },
  {
    "id": "getting-started",
    "title": "Getting Started",
    "path": "/docs/getting-started",
    "description": "Get started with podbox — prebuilt profiles, custom builds, and daily usage.",
    "headings": [
      {
        "id": "getting-started",
        "text": "Getting Started",
        "level": 1
      },
      {
        "id": "installation",
        "text": "Installation",
        "level": 2
      },
      {
        "id": "before-you-start",
        "text": "Before you start",
        "level": 2
      },
      {
        "id": "two-ways-to-create-a-container",
        "text": "Two Ways to Create a Container",
        "level": 2
      },
      {
        "id": "prebuilt-quick-start",
        "text": "Prebuilt (Quick Start)",
        "level": 2
      },
      {
        "id": "available-profiles",
        "text": "Available profiles",
        "level": 3
      },
      {
        "id": "non-interactive",
        "text": "Non-interactive",
        "level": 3
      },
      {
        "id": "interactive",
        "text": "Interactive",
        "level": 3
      },
      {
        "id": "verify-it-works",
        "text": "Verify it works",
        "level": 3
      },
      {
        "id": "what-happens",
        "text": "What happens",
        "level": 3
      },
      {
        "id": "custom-build-from-base",
        "text": "Custom (Build from Base)",
        "level": 2
      },
      {
        "id": "non-interactive-1",
        "text": "Non-interactive",
        "level": 3
      },
      {
        "id": "interactive-1",
        "text": "Interactive",
        "level": 3
      },
      {
        "id": "container-naming",
        "text": "Container naming",
        "level": 3
      },
      {
        "id": "custom-config-example",
        "text": "Custom config example",
        "level": 3
      },
      {
        "id": "inspect-what-was-generated",
        "text": "Inspect what was generated",
        "level": 3
      },
      {
        "id": "check-for-drift",
        "text": "Check for drift",
        "level": 3
      },
      {
        "id": "what-happens-1",
        "text": "What happens",
        "level": 3
      },
      {
        "id": "daily-usage",
        "text": "Daily Usage",
        "level": 2
      },
      {
        "id": "active-context",
        "text": "Active context",
        "level": 3
      },
      {
        "id": "open-a-shell",
        "text": "Open a shell",
        "level": 3
      },
      {
        "id": "run-commands",
        "text": "Run commands",
        "level": 3
      },
      {
        "id": "export-to-host",
        "text": "Export to host",
        "level": 3
      },
      {
        "id": "resource-usage",
        "text": "Resource usage",
        "level": 3
      },
      {
        "id": "snapshots",
        "text": "Snapshots",
        "level": 3
      },
      {
        "id": "path-translation",
        "text": "Path translation",
        "level": 3
      },
      {
        "id": "troubleshoot",
        "text": "Troubleshoot",
        "level": 3
      },
      {
        "id": "lifecycle-management",
        "text": "Lifecycle Management",
        "level": 2
      },
      {
        "id": "understanding-the-chain",
        "text": "Understanding the chain",
        "level": 3
      },
      {
        "id": "preview-without-side-effects",
        "text": "Preview without side effects",
        "level": 3
      },
      {
        "id": "quadlet-persistence",
        "text": "Quadlet persistence",
        "level": 3
      },
      {
        "id": "start-and-stop",
        "text": "Start and stop",
        "level": 3
      },
      {
        "id": "remove",
        "text": "Remove",
        "level": 3
      },
      {
        "id": "update-and-rebuild",
        "text": "Update and rebuild",
        "level": 3
      },
      {
        "id": "edit-config-interactively",
        "text": "Edit config interactively",
        "level": 3
      },
      {
        "id": "commands-at-a-glance",
        "text": "Commands at a Glance",
        "level": 2
      },
      {
        "id": "profiles",
        "text": "Profiles",
        "level": 3
      },
      {
        "id": "creating-and-building",
        "text": "Creating and building",
        "level": 3
      },
      {
        "id": "running-and-entering",
        "text": "Running and entering",
        "level": 3
      },
      {
        "id": "managing-state",
        "text": "Managing state",
        "level": 3
      },
      {
        "id": "exporting",
        "text": "Exporting",
        "level": 3
      },
      {
        "id": "diagnostics-and-utilities",
        "text": "Diagnostics and utilities",
        "level": 3
      },
      {
        "id": "next-steps",
        "text": "Next Steps",
        "level": 2
      }
    ]
  },
  {
    "id": "guest",
    "title": "Guest daemon",
    "path": "/docs/guest",
    "description": "podbox-guest daemon internals — startup sequence, event loop, socket protocol, and interceptors for notifications, clipboard, xdg-open, and host-exec.",
    "headings": [
      {
        "id": "guest-daemon",
        "text": "Guest daemon",
        "level": 1
      },
      {
        "id": "entry-point",
        "text": "Entry point",
        "level": 2
      },
      {
        "id": "daemon-startup",
        "text": "Daemon startup",
        "level": 2
      },
      {
        "id": "event-loop",
        "text": "Event loop",
        "level": 3
      },
      {
        "id": "socket-protocol",
        "text": "Socket protocol",
        "level": 2
      },
      {
        "id": "interceptors",
        "text": "Interceptors",
        "level": 2
      },
      {
        "id": "symlink-dispatch",
        "text": "Symlink dispatch",
        "level": 3
      },
      {
        "id": "host-exec-security",
        "text": "Host-exec security",
        "level": 3
      }
    ]
  },
  {
    "id": "index",
    "title": "Documentation",
    "path": "/docs",
    "description": "",
    "headings": [
      {
        "id": "documentation",
        "text": "Documentation",
        "level": 1
      },
      {
        "id": "user-guides",
        "text": "User Guides",
        "level": 2
      },
      {
        "id": "reference",
        "text": "Reference",
        "level": 2
      },
      {
        "id": "quick-reference",
        "text": "Quick Reference",
        "level": 2
      }
    ]
  },
  {
    "id": "protocol",
    "title": "Host-Guest Socket Protocol",
    "path": "/docs/protocol",
    "description": "podbox host-guest Unix socket protocol — wire format, handshake, message types, capability negotiation, and notify action callbacks.",
    "headings": [
      {
        "id": "host-guest-socket-protocol",
        "text": "Host-Guest Socket Protocol",
        "level": 1
      },
      {
        "id": "wire-format",
        "text": "Wire Format",
        "level": 2
      },
      {
        "id": "socket-location",
        "text": "Socket Location",
        "level": 2
      },
      {
        "id": "handshake",
        "text": "Handshake",
        "level": 2
      },
      {
        "id": "message-types",
        "text": "Message Types",
        "level": 2
      },
      {
        "id": "guest-host",
        "text": "Guest → Host",
        "level": 3
      },
      {
        "id": "host-guest",
        "text": "Host → Guest",
        "level": 3
      },
      {
        "id": "notify-actions",
        "text": "Notify actions",
        "level": 2
      },
      {
        "id": "capabilities",
        "text": "Capabilities",
        "level": 2
      }
    ]
  },
  {
    "id": "quadlet",
    "title": "Quadlet reference",
    "path": "/docs/quadlet",
    "description": "Reference for the systemd Quadlet units generated by podbox — .container, .build, .socket, and companion .service files with all supported keys.",
    "headings": [
      {
        "id": "quadlet-reference",
        "text": "Quadlet reference",
        "level": 1
      },
      {
        "id": "build-file",
        "text": ".build file",
        "level": 2
      },
      {
        "id": "socket-file",
        "text": ".socket file",
        "level": 2
      },
      {
        "id": "container-file",
        "text": ".container file",
        "level": 2
      },
      {
        "id": "unit",
        "text": "[Unit]",
        "level": 3
      },
      {
        "id": "container",
        "text": "[Container]",
        "level": 3
      },
      {
        "id": "environment-entries",
        "text": "Environment= entries",
        "level": 3
      },
      {
        "id": "volume-entries",
        "text": "Volume= entries",
        "level": 3
      },
      {
        "id": "podmanargs",
        "text": "PodmanArgs=",
        "level": 3
      },
      {
        "id": "service",
        "text": "[Service]",
        "level": 3
      },
      {
        "id": "install",
        "text": "[Install]",
        "level": 3
      },
      {
        "id": "companion-service-files",
        "text": "Companion .service files",
        "level": 2
      },
      {
        "id": "name-hostservice",
        "text": "<name>-host.service",
        "level": 3
      },
      {
        "id": "name-proxyservice-d-bus-proxy",
        "text": "<name>-proxy.service (D-Bus proxy)",
        "level": 3
      },
      {
        "id": "name-compositorservice-wayland-firewall",
        "text": "<name>-compositor.service (Wayland firewall)",
        "level": 3
      },
      {
        "id": "podman-version-targeting",
        "text": "Podman Version Targeting",
        "level": 2
      },
      {
        "id": "important-notes",
        "text": "Important Notes",
        "level": 2
      }
    ]
  },
  {
    "id": "troubleshooting",
    "title": "Troubleshooting",
    "path": "/docs/troubleshooting",
    "description": "Fix common podbox issues — find your symptom, run the fix.",
    "headings": [
      {
        "id": "troubleshooting",
        "text": "Troubleshooting",
        "level": 1
      },
      {
        "id": "quick-recovery",
        "text": "Quick recovery",
        "level": 2
      },
      {
        "id": "container-wont-start",
        "text": "Container won't start",
        "level": 2
      },
      {
        "id": "d-bus-proxy-fails-or-container-hangs-on-startup",
        "text": "D-Bus proxy fails or container hangs on startup",
        "level": 2
      },
      {
        "id": "gui-apps-dont-appear-wayland-socket-errors",
        "text": "GUI apps don't appear / Wayland socket errors",
        "level": 2
      },
      {
        "id": "interceptors-not-working",
        "text": "Interceptors not working",
        "level": 2
      },
      {
        "id": "uid-mismatch-or-permission-errors",
        "text": "UID mismatch or permission errors",
        "level": 2
      },
      {
        "id": "ssh-agent-not-forwarding",
        "text": "SSH agent not forwarding",
        "level": 2
      },
      {
        "id": "build-fails-or-produces-a-stale-image",
        "text": "Build fails or produces a stale image",
        "level": 2
      },
      {
        "id": "container-starts-but-podbox-shell-hangs",
        "text": "Container starts but podbox shell hangs",
        "level": 2
      },
      {
        "id": "commands-target-the-wrong-container",
        "text": "Commands target the wrong container",
        "level": 2
      }
    ]
  }
];
