ARG BASE_IMAGE=docker.io/library/fedora:44
FROM ${BASE_IMAGE}

ARG TARGETPLATFORM

ENV PODBOX_CONTAINER=1
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8

COPY $TARGETPLATFORM/podbox-guest /usr/local/bin/podbox-guest

RUN dnf install -y \
    sudo curl wget tar unzip which coreutils \
    diffutils findutils grep sed gawk bash-completion \
    fish fastfetch glibc-all-langpacks \
 && dnf clean all

RUN chmod +x /usr/local/bin/podbox-guest

ENTRYPOINT ["/usr/local/bin/podbox-guest", "--entry"]
CMD ["/usr/bin/fish"]